/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as Mkt701RouteImport } from './routes/mkt701'
import { Route as MayoristaRouteImport } from './routes/mayorista'
import { Route as CartRouteImport } from './routes/cart'
import { Route as R701managerRouteImport } from './routes/701manager'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R701managerIndexRouteImport } from './routes/701manager.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as R701managerProductsRouteImport } from './routes/701manager.products'
import { Route as R701managerOrdersRouteImport } from './routes/701manager.orders'
import { Route as R701managerAnalyticsRouteImport } from './routes/701manager.analytics'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const Mkt701Route = Mkt701RouteImport.update({
  id: '/mkt701',
  path: '/mkt701',
  getParentRoute: () => rootRouteImport,
} as any)
const MayoristaRoute = MayoristaRouteImport.update({
  id: '/mayorista',
  path: '/mayorista',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const R701managerRoute = R701managerRouteImport.update({
  id: '/701manager',
  path: '/701manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R701managerIndexRoute = R701managerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => R701managerRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const R701managerProductsRoute = R701managerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => R701managerRoute,
} as any)
const R701managerOrdersRoute = R701managerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => R701managerRoute,
} as any)
const R701managerAnalyticsRoute = R701managerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => R701managerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/701manager': typeof R701managerRouteWithChildren
  '/cart': typeof CartRoute
  '/mayorista': typeof MayoristaRoute
  '/mkt701': typeof Mkt701Route
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/701manager/analytics': typeof R701managerAnalyticsRoute
  '/701manager/orders': typeof R701managerOrdersRoute
  '/701manager/products': typeof R701managerProductsRoute
  '/product/$id': typeof ProductIdRoute
  '/701manager/': typeof R701managerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/mayorista': typeof MayoristaRoute
  '/mkt701': typeof Mkt701Route
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/701manager/analytics': typeof R701managerAnalyticsRoute
  '/701manager/orders': typeof R701managerOrdersRoute
  '/701manager/products': typeof R701managerProductsRoute
  '/product/$id': typeof ProductIdRoute
  '/701manager': typeof R701managerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/701manager': typeof R701managerRouteWithChildren
  '/cart': typeof CartRoute
  '/mayorista': typeof MayoristaRoute
  '/mkt701': typeof Mkt701Route
  '/shop': typeof ShopRoute
  '/wishlist': typeof WishlistRoute
  '/701manager/analytics': typeof R701managerAnalyticsRoute
  '/701manager/orders': typeof R701managerOrdersRoute
  '/701manager/products': typeof R701managerProductsRoute
  '/product/$id': typeof ProductIdRoute
  '/701manager/': typeof R701managerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/701manager'
    | '/cart'
    | '/mayorista'
    | '/mkt701'
    | '/shop'
    | '/wishlist'
    | '/701manager/analytics'
    | '/701manager/orders'
    | '/701manager/products'
    | '/product/$id'
    | '/701manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/mayorista'
    | '/mkt701'
    | '/shop'
    | '/wishlist'
    | '/701manager/analytics'
    | '/701manager/orders'
    | '/701manager/products'
    | '/product/$id'
    | '/701manager'
  id:
    | '__root__'
    | '/'
    | '/701manager'
    | '/cart'
    | '/mayorista'
    | '/mkt701'
    | '/shop'
    | '/wishlist'
    | '/701manager/analytics'
    | '/701manager/orders'
    | '/701manager/products'
    | '/product/$id'
    | '/701manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R701managerRoute: typeof R701managerRouteWithChildren
  CartRoute: typeof CartRoute
  MayoristaRoute: typeof MayoristaRoute
  Mkt701Route: typeof Mkt701Route
  ShopRoute: typeof ShopRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mkt701': {
      id: '/mkt701'
      path: '/mkt701'
      fullPath: '/mkt701'
      preLoaderRoute: typeof Mkt701RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mayorista': {
      id: '/mayorista'
      path: '/mayorista'
      fullPath: '/mayorista'
      preLoaderRoute: typeof MayoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/701manager': {
      id: '/701manager'
      path: '/701manager'
      fullPath: '/701manager'
      preLoaderRoute: typeof R701managerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/701manager/': {
      id: '/701manager/'
      path: '/'
      fullPath: '/701manager/'
      preLoaderRoute: typeof R701managerIndexRouteImport
      parentRoute: typeof R701managerRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/701manager/products': {
      id: '/701manager/products'
      path: '/products'
      fullPath: '/701manager/products'
      preLoaderRoute: typeof R701managerProductsRouteImport
      parentRoute: typeof R701managerRoute
    }
    '/701manager/orders': {
      id: '/701manager/orders'
      path: '/orders'
      fullPath: '/701manager/orders'
      preLoaderRoute: typeof R701managerOrdersRouteImport
      parentRoute: typeof R701managerRoute
    }
    '/701manager/analytics': {
      id: '/701manager/analytics'
      path: '/analytics'
      fullPath: '/701manager/analytics'
      preLoaderRoute: typeof R701managerAnalyticsRouteImport
      parentRoute: typeof R701managerRoute
    }
  }
}

interface R701managerRouteChildren {
  R701managerAnalyticsRoute: typeof R701managerAnalyticsRoute
  R701managerOrdersRoute: typeof R701managerOrdersRoute
  R701managerProductsRoute: typeof R701managerProductsRoute
  R701managerIndexRoute: typeof R701managerIndexRoute
}

const R701managerRouteChildren: R701managerRouteChildren = {
  R701managerAnalyticsRoute: R701managerAnalyticsRoute,
  R701managerOrdersRoute: R701managerOrdersRoute,
  R701managerProductsRoute: R701managerProductsRoute,
  R701managerIndexRoute: R701managerIndexRoute,
}

const R701managerRouteWithChildren = R701managerRoute._addFileChildren(
  R701managerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R701managerRoute: R701managerRouteWithChildren,
  CartRoute: CartRoute,
  MayoristaRoute: MayoristaRoute,
  Mkt701Route: Mkt701Route,
  ShopRoute: ShopRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
